services:
  - type: web
    name: portfolio-camilo
    env: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: node ./dist/server/entry.mjs
    rootDir: .
